# Estágio de Build
FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src

# Copia e restaura dependências
COPY ["WebDiario.csproj", "./"]
RUN dotnet restore "WebDiario.csproj"

# Copia o restante dos arquivos e publica
COPY . .
RUN dotnet publish "WebDiario.csproj" -c Release -o /app/publish /p:UseAppHost=false

# Estágio de Execução (Runtime leve)
FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS final
WORKDIR /app
EXPOSE 8080
ENV ASPNETCORE_URLS=http://+:8080

COPY --from=build /app/publish .

ENTRYPOINT ["dotnet", "WebDiario.dll"]